name: env_sphere
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pydicom=2.1.2  # DICOM
  - pylibjpeg=1.3.0 # To Handle DICOM Pixel Data compression
  - pylibjpeg-libjpeg=1.2.0 # To Handle DICOM Pixel Data compression
  - pylibjpeg-rle=1.1.0 # To Handle DICOM Pixel Data compression
  - pylibjpeg-openjpeg=1.1.1 # To Handle DICOM Pixel Data compression
  - sqlalchemy=1.3.13  # Database
  - Django=3.0.2  # API
  - djangorestframework=3.11.0  # API
  - uritemplate=3.0.1  # API (Generating an OpenAPI Schema)
  - requests=2.23.0
  - PyYAML=5.3  # Yaml
  - colorlog=4.1.0  # Log formatting with colors
  - psutil=5.6.7  # Process and system utilities
  - pip:
    - pynetdicom==1.5.5  # DICOM
    - sqlalchemy-views==0.2.4  # Database
    - psycopg2-binary==2.7.5  # Database
    - dirsync==2.2.4  # Directory synchrone