version: '3.8'

services:
  sphere-db:
    image: postgres:latest
    ports:
      - 5432
    environment:
      - POSTGRES_USER=sphere
      - POSTGRES_PASSWORD=spherepwd
    command: -c max_connections=515
    networks:
      - sphere
    volumes:
      - sphere-db-data:/var/lib/postgresql/data
      - ./postgres/volumes/ohif/init:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4:latest
    environment: 
      - PGADMIN_DEFAULT_EMAIL=sphere@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=manager
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=8080
    volumes:
      - ./pgadmin4/volumes/servers.json:/pgadmin4/servers.json:rw
    ports: 
      - 8080:8080
    networks:
      - sphere
    depends_on:
      - sphere-db

  sphere:
    image: localhost/sphere:1.11.1
    environment:
      - DICOM_PORT=11112
      - DICOM_AET=SPHERE-OHIF
      - POSTGRE_HOST=sphere-db
      - POSTGRE_PORT=5432
      - POSTGRE_NAME=sphere
      - POSTGRE_SCHEMA=pacs
      - POSTGRE_LOGIN=sphere
      - POSTGRE_PASSWORD=spherepwd
      - API_SERVER_ENABLED=True
      - API_SERVER_LISTENING_IP=0.0.0.0
      - API_SERVER_LISTENING_PORT=8081
      - API_DICOMWEB_ENABLED=True
      - ALLOWED_HOSTS=127.0.0.1, localhost, *, sphere
      - API_JWT_VALIDATION=False
      - LOG_STREAM_LEVEL=DEBUG
    volumes:
      - ./sphere/volumes/dev/conf-pacs_1:/opt/sphere/pacs/app:rw
      - ./sphere/volumes/dev/data-pacs_1:/opt/sphere/pacs/data:rw
    ports:
      - 11112
      - 8081
    networks:
      - sphere
    depends_on:
      - sphere-db

  ohif-viewer:
    image: ohif/viewer:latest
    volumes: 
      - ./ohif/volumes/conf/app-config.js:/usr/share/nginx/html/app-config.js:rw
      - ./ohif/volumes/conf/nginx.conf:/etc/nginx/conf.d/default.conf:rw
    ports: 
      - 8085:3000
      - 8081:8081
    networks:
      - sphere
    depends_on:
      - sphere


volumes:
    sphere-db-data:
      driver: local

networks:
  sphere:
    driver: bridge