"""
Django settings for web_service project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
# Built-in/Generic Imports
import os
import sys

# Own modules
from sphere.settings import L_ALLOWED_HOSTS, DB_PARAMS


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Path of the project SPHERE
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))))))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3k!tnt*y7#yk77ntuzd+!%!&)=)85%33ipa(&l4ds_x2vgva4^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = L_ALLOWED_HOSTS

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'api_annotation',
    'api_sphere_dicomweb',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    # 'default': {  # test
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    # 'default': {  # dev
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'OPTIONS': {
    #         'options': '-c search_path=public'
    #     },
    #     'NAME': 'pacs1',
    #     'USER': 'postgres',
    #     'PASSWORD': 'password',
    #     'HOST': '127.0.0.1',
    #     'PORT': '5432'
    # }
    # 'default': {  # dev pacs
    #         'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #         'OPTIONS': {
    #             'options': '-c search_path=sphere_oac_pacs1'
    #         },
    #         'NAME': 'pacs',
    #         'USER': 'oachouri',
    #         'PASSWORD': 'C833MpXMqwn6G43m',
    #         'HOST': '10.172.146.19',
    #         'PORT': '5432'
    #     }
    'default': {  # Param of settings.yml
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'OPTIONS': {
                'options': '-c search_path=' + DB_PARAMS['schema']
            },
            'NAME': DB_PARAMS['database'],
            'USER': DB_PARAMS['login'],
            'PASSWORD': DB_PARAMS['password'],
            'HOST': DB_PARAMS['ip'],
            'PORT': str(DB_PARAMS['port'])
        }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# fixtures pour les tests:

FIXTURE_DIRS = ['api_sphere_dicomweb/test/fixtures']

